[build-system]
requires = ["setuptools >= 64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "typesum"
version = "0.1.0"
description = "Display any Python object in a readable way"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
    {name = "Maciej Zygmanowski", email = "sppmacd.oss@proton.me"},
]
keywords = ["pretty-print", "debug", "formatting", "utility"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Utilities",
]
dependencies = []

[project.optional-dependencies]
test = ["pytest>=7.0", "numpy>=1.24", "pandas>=2.0", "torch>=2.0"]

[project.urls]
Homepage = "https://github.com/sppmacd/pytypesummary"
Repository = "https://github.com/sppmacd/pytypesummary.git"
Issues = "https://github.com/sppmacd/pytypesummary/issues"

[tool.pytest.ini_options]
testpaths = ["tests"]
